#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->make('Illuminate\Contracts\Console\Kernel')->handle(
	new Symfony\Component\Console\Input\ArgvInput,
	new Symfony\Component\Console\Output\ConsoleOutput
);

exit($status);
