export const BREADCRUMBS_SET = 'BREADCRUMBS_SET'

export const MAGNET_CLICK = 'MAGNET_CLICK'
export const MAGNET_SET = 'MAGNET_SET'
export const MAGNET_UNSET = 'MAGNET_UNSET'
export const MAGNETS_SET = 'MAGNETS_SET'

export const VALIDATION_ERRORS_CLEAR = 'VALIDATION_ERRORS_CLEAR'
export const VALIDATION_ERRORS_SET = 'VALIDATION_ERRORS_SET'
