#!/bin/sh

# exits in case of any error
set -e

cd "$(dirname "$0")/.."

echo "==> Testing for config file..."
if [ ! -f .env ]; then
  echo "==> Config not found!"
  echo "==> Create .env config file from .env.example to continue setup"
  exit 1
fi

echo "==> Installing php dependencies..."
composer install

echo "==> Installing front-end dependencies..."
bower install
