#!/bin/sh

# Выход в случае ошибки
set -e

cd "$(dirname "$0")/.."

echo "==> Installing front-end dependencies..."
cd public
bower install
cd ../

bower install
npm install
gulp --production

echo "==> Ant php linting, css & js compiling..."
ant
