#!/bin/sh

# Выход в случае ошибки
set -e

export NODE_ENV=production

cd "$(dirname "$0")/.."

echo "==> Installing front-end dependencies..."
echo "==> yarn..."
export NODE_ENV=dev
# --ignore-platform для freebsd, так как пакет default-gateway выдает ошибку
yarn install --ignore-platform
export NODE_ENV=production

echo "==> yarn run production..."
yarn run production

# composer global require "hirak/prestissimo:^0.3"
# composer global update
# composer install --no-interaction
# vendor/bin/phpunit --exclude-group pages

# Архив для быстрого деплоя
tar --exclude deploy.tar --exclude .git --exclude node_modules --exclude resources/assets --exclude tests -cf deploy.tar .
