#!/bin/sh

# Выход в случае ошибки
set -e

export NODE_ENV=production

cd "$(dirname "$0")/.."

echo "==> Ant php linting..."
ant

echo "==> Installing front-end dependencies..."
bower install
npm install
gulp --production

# composer global require "hirak/prestissimo:^0.3"
# composer global update
# composer install --no-interaction
# vendor/bin/phpunit --exclude-group pages
