#!/bin/sh

# Выход в случае ошибки
set -e

cd "$(dirname "$0")/.."

# Для ускорения деплоя проект поступил в архиве
tar -xf deploy.tar

# Предварительно в папке проекта должен быть
# размещен файл .env для выполнения миграций

RELEASE_DIR=$(pwd)
ROOT_DIR=$(dirname "$RELEASE_DIR")/..
LIVE_DIR=$ROOT_DIR/live
UPLOADS_DIR=$ROOT_DIR/shared/uploads

if [ ! -f $ROOT_DIR/.env ]; then
  echo "Can't find .env configuration file"
  exit 1
fi

# Файл настроек
ln -s $ROOT_DIR/.env $RELEASE_DIR/.env

# Общая папка для загрузок
if [ -d $UPLOADS_DIR ]; then
  rm -rf $RELEASE_DIR/public/uploads
else
  mv $RELEASE_DIR/public/uploads $UPLOADS_DIR
fi

ln -s $UPLOADS_DIR $RELEASE_DIR/public/uploads

# Логин и пароль должны быть переданы от билдера
composer config http-basic.nova.laravel.com "${NOVA_USERNAME}" "${NOVA_PASSWORD}"

# Установка зависимостей
cd $RELEASE_DIR
composer install --no-dev --no-interaction --optimize-autoloader

if [ $? -ne 0 ]; then
  echo "Composer install run was not successful"
  exit 1
fi

# Миграция базы данных
php artisan migrate --force

if [ $? -ne 0 ]; then
  echo "Migration was not completed"
  exit 1
fi

php artisan nova:publish
php artisan config:cache
php artisan route:cache
php artisan view:cache

ln -hfs $RELEASE_DIR $LIVE_DIR

php artisan queue:restart

# На память остается всего 3 релиза
cd $ROOT_DIR/releases
rm -rf $(ls -t | tail -n +4)
