#!/bin/sh

set -o errexit

cd "$(dirname "$0")/../.."

echo "==> Deleting installed ivacuum/generic package..."
rm -rf hosting/vendor/ivacuum/generic

echo "==> Symlinking local ivacuum/generic package..."
ln -s $(pwd)/generic hosting/vendor/ivacuum/generic
