#!/bin/sh

# exits in case of any error
set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Refreshing and migrating database..."
php artisan migrate:refresh

echo "==> Dependencies and db are up"
echo "==> Now are able to run local development server by executing script/server"
